config/routes.rb
Adnetwork::Application.routes.draw do
  resources :ad_venders do
    resources :artwork_distributions
    collection { get :indexOfSize }
    member { get :export }
  end
  resources :vender_feedbacks, :except => [:edit, :update]
  resources :analytic_sums, :only => :index do
    resources :analytic_data, :only => :index
  end
  resources :resolutions
  resources :artworks
  resources :products

  root :to => "home#index"
  devise_for :users

end

app/models/resolution.rb
class Resolution < ActiveRecord::Base
  attr_accessible :resolution
  validates :resolution,
            :format => { :with => /\d+x\d+/, :message => "Invalid format, please use format like 400x300!" },
            :uniqueness => true,
            :presence => true
end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  # GET /resolutions
  # GET /resolutions.json
  def index
    @resolutions = Resolution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resolutions }
    end
  end

  # GET /resolutions/new
  # GET /resolutions/new.json
  def new
    @resolution = Resolution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resolution }
    end
  end

  # GET /resolutions/1/edit
  def edit
    @resolution = Resolution.find(params[:id])
  end

  # POST /resolutions
  # POST /resolutions.json
  def create
    @resolution = Resolution.new(params[:resolution])

    respond_to do |format|
      if @resolution.save
        format.html { redirect_to resolutions_path, notice: 'Resolution was successfully created.' }
        format.json { render json: @resolution, status: :created, location: @resolution }
      else
        format.html { render action: "new" }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resolutions/1
  # PUT /resolutions/1.json
  def update
    @resolution = Resolution.find(params[:id])

    respond_to do |format|
      if @resolution.update_attributes(params[:resolution])
        format.html { redirect_to resolutions_path, notice: 'Resolution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resolutions/1
  # DELETE /resolutions/1.json
  def destroy
    @resolution = Resolution.find(params[:id])
    @resolution.destroy

    respond_to do |format|
      format.html { redirect_to resolutions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/views/resolutions/_form.html.haml
= form_for @resolution, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'layouts/error', :object => @resolution
  .field.control-group
    = f.label :resolution, :class => 'control-label'
    .controls
      = f.text_field :resolution
  %hr
  .actions.control-group
    .controls
      = f.submit 'Save', :class => 'btn btn-primary'
      = link_to 'Back', resolutions_path, :class => 'btn'

app/views/resolutions/edit.html.haml
.titlebar
  %h1.pull-left Editing Resolution

%hr

= render 'form'

app/views/resolutions/index.html.haml
.titlebar
  %h1.pull-left Listing Resolutions
  = link_to 'New Resolution', new_resolution_path, :class => 'btn btn-success pull-right new-btn'

%hr

%table.table.table-striped.table-bordered
  %tr
    %th Resolution
    %th.action
    %th.action

  - @resolutions.each do |resolution|
    %tr
      %td= resolution.resolution
      %td.action= link_to 'Edit', edit_resolution_path(resolution)
      %td.action= link_to 'Destroy', resolution, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/resolutions/new.html.haml
.titlebar
  %h1.pull-left New Resolution

%hr

= render 'form'

app/views/resolutions/show.html.haml
%p#notice= notice

%p
  %b Resolution:
  = @resolution.resolution

= link_to 'Edit', edit_resolution_path(@resolution)
\|
= link_to 'Back', resolutions_path