config/routes.rb
Adnetwork::Application.routes.draw do
  resources :ad_venders do
    resources :artwork_distributions
    collection { get :indexOfSize }
    member { get :export }
  end
  resources :vender_feedbacks, :except => [:edit, :update]
  resources :analytic_sums, :only => :index do
    resources :analytic_data, :only => :index
  end
  resources :resolutions
  resources :artworks
  resources :products

  root :to => "home#index"
  devise_for :users

end

app/models/vender_feedback.rb
require 'chronic'

class VenderFeedback < ActiveRecord::Base
  attr_accessible :chart, :platform, :analytic_data, :product, :ad_vender

  belongs_to :product
  belongs_to :ad_vender

  has_many :analytic_data, :dependent => :destroy

  mount_uploader :chart, ChartUploader

  validates :chart, :presence => true
  validate :csv_format

  after_save :import_csv

  def csv_format
    parser = parser('gdn')
    return unless self.chart_changed?
    csv = Roo::Csv.new(chart.current_path)
    # check titles
    errors.add(:chart, "Expect Header: #{parser[:titles].join('|')}") and return if csv.first != parser[:titles]
    # check body, require all fields present
    csv.each_with_index do |row, i|
      next if i == 0
      all_fields_present = parser[:index].reduce(true) { |s, (k, v)| s &= row[v] }
      errors.add(:chart, "please check line #{i}") unless all_fields_present
      errors.add(:chart, "line #{i+1}: product doesn't exist") unless Product.where(:name => row[parser[:index][:product_name]]).exists?
      errors.add(:chart, "line #{i+1}: artwork doesn't exist") unless Artwork.where(:id => row[parser[:index][:artwork_id]]).exists?
      errors.add(:chart, "line #{i+1}: ad_vender doesn't exist") unless AdVender.where(:name => row[parser[:index][:ad_vender_name]]).exists?
    end
  end

  def import_csv
    return unless self.chart_changed?
    parser = parser('gdn')
    csv = Roo::Csv.new(chart.current_path)
    csv.each_with_index do |row, i|
      next if i == 0
      product      = Product.where(:name => row[parser[:index][:product_name]]).first
      artwork      = Artwork.where(:id => row[parser[:index][:artwork_id]]).first
      ad_vender    = AdVender.where(:name => row[parser[:index][:ad_vender_name]]).first
      platform     = row[parser[:index][:platform]].downcase
      report_date  = Chronic.parse row[parser[:index][:report_date]]
      country_code = row[parser[:index][:country_code]].upcase

      ad = AnalyticDatum.where(
        :product_id         => product.id,
        :artwork_id         => artwork.id,
        :ad_vender_id       => ad_vender.id,
        :vender_feedback_id => self.id,
        :platform           => platform,
        :report_date        => report_date,
        :country_code       => country_code
      ).first_or_initialize

      ad.impression += row[parser[:index][:impression]].gsub(/,/, '').to_i
      ad.click      += row[parser[:index][:click]].gsub(/,/, '').to_i
      ad.install    += row[parser[:index][:install]].gsub(/,/, '').to_i
      ad.cost       += row[parser[:index][:cost]].gsub(/[,$]/, '').to_f
      ad.save
    end
  end

  def parser(vender)
    YAML.load_file("#{Rails.root}/config/csv_parser.yml")[vender].with_indifferent_access
  end
end

app/controllers/vender_feedbacks_controller.rb
class VenderFeedbacksController < ApplicationController
  layout :false
  # GET /vender_feedbacks
  # GET /vender_feedbacks.json
  def index
    @vender_feedbacks = VenderFeedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vender_feedbacks }
    end
  end

  # GET /vender_feedbacks/1
  # GET /vender_feedbacks/1.json
  def show
    @vender_feedback = VenderFeedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vender_feedback }
    end
  end

  # GET /vender_feedbacks/new
  # GET /vender_feedbacks/new.json
  def new
    @vender_feedback = VenderFeedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vender_feedback }
    end
  end

  # GET /vender_feedbacks/1/edit
  def edit
    @vender_feedback = VenderFeedback.find(params[:id])
  end

  # POST /vender_feedbacks
  # POST /vender_feedbacks.json
  def create
    @vender_feedback = VenderFeedback.new(params[:vender_feedback])

    respond_to do |format|
      if @vender_feedback.save
        format.html { redirect_to @vender_feedback, notice: 'Vender feedback was successfully created.' }
        format.json { render json: @vender_feedback, status: :created, location: @vender_feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @vender_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vender_feedbacks/1
  # PUT /vender_feedbacks/1.json
  def update
    @vender_feedback = VenderFeedback.find(params[:id])

    respond_to do |format|
      if @vender_feedback.update_attributes(params[:vender_feedback])
        format.html { redirect_to @vender_feedback, notice: 'Vender feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vender_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vender_feedbacks/1
  # DELETE /vender_feedbacks/1.json
  def destroy
    @vender_feedback = VenderFeedback.find(params[:id])
    @vender_feedback.destroy

    respond_to do |format|
      format.html { redirect_to vender_feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vender_feedbacks_helper.rb
module VenderFeedbacksHelper
end

app/views/vender_feedbacks/_form.html.haml
= form_for @vender_feedback, :html => { :multipart => true } do |f|
  - if @vender_feedback.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vender_feedback.errors.count, "error")} prohibited this vender_feedback from being saved:"
      %ul
        - @vender_feedback.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :platform
    = f.text_field :platform
  .field
    = f.label :chart
    = f.file_field :chart
  .actions
    = f.submit 'Save'

app/views/vender_feedbacks/edit.html.haml
%h1 Editing vender_feedback

= render 'form'

= link_to 'Show', @vender_feedback
\|
= link_to 'Back', vender_feedbacks_path

app/views/vender_feedbacks/index.html.haml
!!!5
%html
  %head
    %title Adnetwork
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/topbar'
    #main-body.container-fluid
      .row-fluid
        %h1 Listing vender_feedbacks
        
        %table
          %tr
            %th Chart
            %th
            %th
        
          - @vender_feedbacks.each do |vender_feedback|
            %tr
              %td= vender_feedback.chart
              %td= link_to 'Show', vender_feedback
              %td= link_to 'Destroy', vender_feedback, :method => :delete, :data => { :confirm => 'Are you sure?' }
        
        %br
        
        = link_to 'New Vender feedback', new_vender_feedback_path

app/views/vender_feedbacks/new.html.haml
%h1 New vender_feedback

= render 'form'

= link_to 'Back', vender_feedbacks_path

app/views/vender_feedbacks/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @vender_feedback.product
%p
  %b Ad vender:
  = @vender_feedback.ad_vender
%p
  %b Platform:
  = @vender_feedback.platform
%p
  %b Chart:
  = @vender_feedback.chart

\|
= link_to 'Back', vender_feedbacks_path