config/routes.rb
Adnetwork::Application.routes.draw do
  resources :ad_venders do
    resources :artwork_distributions
    collection { get :indexOfSize }
    member { get :export }
  end
  resources :vender_feedbacks, :except => [:edit, :update]
  resources :analytic_sums, :only => :index do
    resources :analytic_data, :only => :index
  end
  resources :resolutions
  resources :artworks
  resources :products

  root :to => "home#index"
  devise_for :users

end

app/models/ad_vender.rb
require 'zip/zip'

class AdVender < ActiveRecord::Base
  attr_accessible :name, :artwork_size_list
  acts_as_taggable_on :artwork_sizes

  has_many :artwork_distributions, :dependent => :destroy
  has_many :artworks, :through => :artwork_distributions
  has_many :analytic_data

  validates_uniqueness_of :name

  def artworks_package(platform, product_id)
    latest_ad    = ArtworkDistribution.artworks_for(self.id, platform, product_id).first
    return false unless latest_ad
    latest_ads   = ArtworkDistribution.artworks_for(self.id, platform, product_id).with_version(latest_ad.version)
    package_name = File.join Rails.root, "/tmp/#{name}_#{platform}_#{Product.find(product_id).name}_#{Time.now.strftime("%Y%m%d")}.zip"

    File.delete(package_name) if File.exist?(package_name)

    Zip::ZipFile.open(package_name, Zip::ZipFile::CREATE) do |zipfile|
      latest_ads.each do |ad|
        path = ad.artwork.artwork.current_path
        zipfile.add("#{ad.artwork.id}_#{File.basename(path)}", path)
      end
    end
    package_name
  end

end

app/controllers/ad_venders_controller.rb
class AdVendersController < ApplicationController
  # GET /ad_venders
  # GET /ad_venders.json
  def index
    @ad_venders = AdVender.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ad_venders }
    end
  end

  def export
    @ad_vender = AdVender.find(params[:id])
    package_path = @ad_vender.artworks_package(params[:platform], params[:product_id])
    if package_path
      send_file package_path
    else
      redirect_to :back, :alert => 'No avaliable Artworks'
    end
  end

  def indexOfSize
    @ad_venders = AdVender.tagged_with params[:size]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad_venders }
    end

  end

  # GET /ad_venders/new
  # GET /ad_venders/new.json
  def new
    @ad_vender = AdVender.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad_vender }
    end
  end

  # GET /ad_venders/1/edit
  def edit
    @ad_vender = AdVender.find(params[:id])
  end

  # POST /ad_venders
  # POST /ad_venders.json
  def create
    params[:ad_vender][:artwork_size_list] = params['hidden-ad_vender'][:artwork_size_list]
    @ad_vender = AdVender.new(params[:ad_vender])

    respond_to do |format|
      if @ad_vender.save
        format.html { redirect_to ad_venders_path, notice: 'Ad vender was successfully created.' }
        format.json { render json: @ad_vender, status: :created, location: @ad_vender }
      else
        format.html { render action: "new" }
        format.json { render json: @ad_vender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ad_venders/1
  # PUT /ad_venders/1.json
  def update
    @ad_vender = AdVender.find(params[:id])
    params[:ad_vender][:artwork_size_list] = params['hidden-ad_vender'][:artwork_size_list]

    respond_to do |format|
      if @ad_vender.update_attributes(params[:ad_vender])
        format.html { redirect_to ad_venders_path, notice: 'Ad vender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad_vender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_venders/1
  # DELETE /ad_venders/1.json
  def destroy
    @ad_vender = AdVender.find(params[:id])
    @ad_vender.destroy

    respond_to do |format|
      format.html { redirect_to ad_venders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ad_venders_helper.rb
module AdVendersHelper
end

app/views/ad_venders/_form.html.haml
= form_for @ad_vender, :html => { :class => 'form-horizontal' } do |f|
  - if @ad_vender.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ad_vender.errors.count, "error")} prohibited this ad_vender from being saved:"
      %ul
        - @ad_vender.errors.full_messages.each do |msg|
          %li= msg

  .field.control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name
  %hr
  .field.control-group
    = f.label :artwork_size_list, :class => 'control-label'
    .controls
      = f.text_field :artwork_size_list, :autocomplete => "off", :class => 'tagManager'
  %hr
  .actions.control-group
    .controls
      = f.submit 'Save', :class => 'btn btn-primary'
      = link_to 'Back', ad_venders_path, :class => 'btn'

:javascript
  artwork_size_list = "#{@ad_vender.artwork_size_list}";
  type_ahead_source = #{resolution_list};

:coffee
  $(document).ready ->
    $(".tagManager").tagsManager
      prefilled: artwork_size_list.split(',')
      typeahead: true
      typeaheadSource: type_ahead_source

app/views/ad_venders/edit.html.haml
.titlebar
  %h1.pull-left Editing Ad Vender

%hr

= render 'form'

app/views/ad_venders/index.html.haml
.titlebar
  %h1.pull-left Listing Ad Venders
  = link_to 'New Ad vender', new_ad_vender_path, :class => 'btn btn-success pull-right new-btn'

%hr
- if flash[:alert]
  #error_explanation.alert.alert-error
    = flash[:alert]
- if flash[:notice]
  #error_explanation.alert.alert-success
    = flash[:notice]
%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th Required Sizes
    %th.action
    %th.action
    %th.action
    %th.action

  - @ad_venders.each do |ad_vender|
    %tr
      %td= ad_vender.name
      %td= ad_vender.artwork_size_list
      %td.action= link_to 'Artworks', ad_vender_artwork_distributions_path(ad_vender)
      %td.action= link_to 'Export', "#modal-#{ad_vender.id}", {'data-toggle' => 'modal'}
      %td.action= link_to 'Edit', edit_ad_vender_path(ad_vender)
      %td.action= link_to 'Destroy', ad_vender, :method => :delete, :data => { :confirm => 'Are you sure?' }

- @ad_venders.each do |ad_vender|
  .modal.hide.fade{ :id => "modal-#{ad_vender.id}" , :tabindex => "-1", :role => "dialog", 'aria-labelledby' => "modalLabel", 'aria-hidden' => "true"}
    .modal-header
      %button.close{:type => "button", 'data-dismiss' => "modal", 'aria-hidden' => "true"} ×
      %h3#modalLabel Choose Target
    .modal-body
      = form_tag export_ad_vender_path(ad_vender), :method => 'GET', :class => 'form-horizontal' do
        .field.control-group
          = label_tag :platform, 'Platform', :class => 'control-label'
          .controls
            = select_tag :platform, options_for_select([['Android', 'android'], ['iOS', 'ios']], 'ios')
        %hr
        .field.control-group
          = label_tag :product, 'Product', :class => 'control-label'
          .controls
            = select_tag :product_id, options_from_collection_for_select(Product.all, "id", "name")


    .modal-footer
      %button.btn{'data-dismiss' => "modal", 'aria-hidden' => "true"} Close
      %button.btn.btn-primary{:id => "submit-btn-#{ad_vender.id}"} Export

    :coffee
      $("#submit-btn-#{ad_vender.id}").click -> $("#modal-#{ad_vender.id} form").submit()

app/views/ad_venders/new.html.haml
.titlebar
  %h1.pull-left New Ad Vender

%hr

= render 'form'

app/views/ad_venders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ad_vender.name

= link_to 'Edit', edit_ad_vender_path(@ad_vender)
\|
= link_to 'Back', ad_venders_path